/**************************************************************
 * HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 **************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP Stack/TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_CONN curHTTP;
extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern BYTE curHTTPID;

void HTTPPrint(DWORD callbackID);
void HTTPPrint_VTempA(void);
void HTTPPrint_VGazA(void);
void HTTPPrint_VHumiD(void);
void HTTPPrint_VTempD(void);
void HTTPPrint_VBaroI2C(void);
void HTTPPrint_VTempI2C(void);
void HTTPPrint_VLightA(void);

void HTTPPrint(DWORD callbackID)
{
	switch(callbackID)
	{
        case 0x0000000c:
			HTTPPrint_VTempA();
			break;
        case 0x0000000e:
			HTTPPrint_VGazA();
			break;
        case 0x0000000f:
			HTTPPrint_VHumiD();
			break;
        case 0x00000010:
			HTTPPrint_VTempD();
			break;
        case 0x00000011:
			HTTPPrint_VBaroI2C();
			break;
        case 0x00000012:
			HTTPPrint_VTempI2C();
			break;
        case 0x00000013:
			HTTPPrint_VLightA();
			break;
		default:
			// Output notification for undefined values
			TCPPutROMArray(sktHTTP, (ROM BYTE*)"!DEF", 4);
	}

	return;
}

void HTTPPrint_(void)
{
	TCPPut(sktHTTP, '~');
	return;
}

#endif

#endif
